Name: Lavanya Deole

Net ID: lnd2037

Assignment 2

Part 1 - Numpy

In [1]:
import numpy as np

Loading the dataset

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

In [5]:
vertical_stack = np.vstack((A, B))

In [7]:
horizontal_stack = np.hstack((A, B))

In [8]:
print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontal Stack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]

In [9]:
common_elements = np.intersect1d(A, B)
print("Common elements:", common_elements)

Common elements: []


3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [10]:
filtered_A = A[(A >= 5) & (A <= 10)]
print("Numbers in A between 5 and 10:", filtered_A)

Numbers in A between 5 and 10: [5 6]


4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [11]:
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered iris_2d rows:\n", filtered_iris)

Filtered iris_2d rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Part 2 - Pandas

In [12]:
import pandas as pd

Loading the dataset

In [15]:
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv")

1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [16]:
filtered_df = df.iloc[::20, [0, 1, 2]]  # Selecting specific columns by index
print("Filtered rows every 20th row:\n", filtered_df)

Filtered rows every 20th row:
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [18]:
min_price_mean = df["Min.Price"].mean()
max_price_mean = df["Max.Price"].mean()
df = df.copy()
df["Min.Price"] = df["Min.Price"].fillna(min_price_mean)
df["Max.Price"] = df["Max.Price"].fillna(max_price_mean)
print("Min.Price mean:", min_price_mean)
print("Max.Price mean:", max_price_mean)
print("Updated DataFrame with missing values replaced:\n", df.head())

Min.Price mean: 17.11860465116279
Max.Price mean: 21.45909090909091
Updated DataFrame with missing values replaced:
   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186

3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [19]:
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
filtered_rows = df_random[df_random.sum(axis=1) > 100]
print("Rows where sum > 100:\n", filtered_rows)

Rows where sum > 100:
      0   1   2   3
0   32  35  31  20
2   38  34  18  23
4   38  39  30  29
7   38  35  36  26
10  11  21  38  38
11  20  35  39  14
12  27  36  33  36
14  38  33  26  13
